# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-07-20 14:59:36
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def SolarSuitability(Galapagos_Boundary="Parametros\\Provincia_Galapagos_CONALI_2018", PVOUT_tif="Parameters\\PVOUT.tif", Aptitud_con_pediente_y_orientación_preprocesada_="C:\\Solar\\SolarSuitability\\SolarSA\\solar_suitability_1to5.tif", Red_vial="Red_vial_Galapagos_OSM_2023_UTM15S", Subestaciones="C:\\Solar\\HyGalapgos\\Model\\Inputs\\sube.shp", Valor_umbral=3.8, Peso_Potencial_Fotovoltaico=0.5, Peso_Pendiente_y_orientación=0.2, Peso_Distancia_a_las_vias=0.15, Peso_Distancia_a_subestaciones=0.15, cost_raster="C:\\Solar\\SolarSuitability\\Outputs\\cost_raster", pos_sites="memory\\pos_sites", sites_poly_shp_3_="memory\\sites_poly"):  # SolarSuitability

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    A_ECOSISTEMAS_NATIVOS_2016_shp = "C:\\Solar\\HyGalapgos\\cobertura\\A_ECOSISTEMAS_NATIVOS_2016.shp"

    # Process: Distance Accumulation (Distance Accumulation) (sa)
    distacc_roads = "C:\\Solar\\HyGalapgos\\HyGalapagos\\HyGalapagos.gdb\\distacc_roads"
    Distance_Accumulation = distacc_roads
    Output_Back_Direction_Raster = ""
    Output_Source_Direction_Raster = ""
    Output_Source_Location_Raster = ""
    distacc_roads = arcpy.sa.DistanceAccumulation(Red_vial.__str__().format(**locals(),**globals())if isinstance(Red_vial, str) else Red_vial, "", "", "", "", "BINARY 1 -30 30", "", "BINARY 1 45", Output_Back_Direction_Raster, Output_Source_Direction_Raster, Output_Source_Location_Raster, "", "", "", "", "PLANAR")
    distacc_roads.save(Distance_Accumulation)


    # Process: Project Raster (Project Raster) (management)
    PVOUT_reproject = "memory\\PVOUT_ProjectRaster"
    arcpy.management.ProjectRaster(in_raster=PVOUT_tif.__str__().format(**locals(),**globals())if isinstance(PVOUT_tif, str) else PVOUT_tif, out_raster=PVOUT_reproject, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_15S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",-93.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")
    PVOUT_reproject = arcpy.Raster(PVOUT_reproject)

    # Process: Project (2) (Project) (management)
    Provincia_Galapagos_Project = "C:\\Solar\\SolarSuitability\\SolarSA\\SolarSA.gdb\\Provincia_Galapagos__Project"
    arcpy.management.Project(in_dataset=Galapagos_Boundary.__str__().format(**locals(),**globals())if isinstance(Galapagos_Boundary, str) else Galapagos_Boundary, out_dataset=Provincia_Galapagos_Project, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_15S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",-93.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")

    # Process: Clip Raster (Clip Raster) (management)
    clip_pv = "memory\\clip_pv"
    arcpy.management.Clip(in_raster=PVOUT_reproject, rectangle="", out_raster=clip_pv, in_template_dataset=Provincia_Galapagos_Project, clipping_geometry="ClippingGeometry")
    clip_pv = arcpy.Raster(clip_pv)

    # Process: Raster Calculator (Raster Calculator) (sa)
    pv_reclass = "C:\\Solar\\SolarSuitability\\Outputs\\pv_reclass"
    Raster_Calculator = pv_reclass
    pv_reclass = Con(clip_pv > 1700, 5,    Con(clip_pv > 1600, 4,        Con(clip_pv > 1500, 3,            Con(clip_pv > 1400, 2,                1))))
    pv_reclass.save(Raster_Calculator)


    # Process: Raster Calculator (3) (Raster Calculator) (sa)
    roads_reclass = "C:\\Solar\\HyGalapgos\\Model\\Outputs\\roads_reclass"
    Raster_Calculator_3_ = roads_reclass
    roads_reclass = Con(distacc_roads < 1000, 5,    Con(distacc_roads < 3000, 4,        Con(distacc_roads < 10000, 3,            Con(distacc_roads < 20000, 2,                1))))
    roads_reclass.save(Raster_Calculator_3_)


    # Process: Distance Accumulation (3) (Distance Accumulation) (sa)
    dist_acc_sub = "C:\\Solar\\HyGalapgos\\HyGalapagos\\HyGalapagos.gdb\\dist_acc_sub"
    Distance_Accumulation_3_ = dist_acc_sub
    Output_Back_Direction_Raster_3_ = ""
    Output_Source_Direction_Raster_3_ = ""
    Output_Source_Location_Raster_3_ = ""
    dist_acc_sub = arcpy.sa.DistanceAccumulation(Subestaciones.__str__().format(**locals(),**globals())if isinstance(Subestaciones, str) else Subestaciones, "", "", "", "", "BINARY 1 -30 30", "", "BINARY 1 45", Output_Back_Direction_Raster_3_, Output_Source_Direction_Raster_3_, Output_Source_Location_Raster_3_, "", "", "", "", "PLANAR")
    dist_acc_sub.save(Distance_Accumulation_3_)


    # Process: Raster Calculator (5) (Raster Calculator) (sa)
    subest_reclass = "C:\\Solar\\HyGalapgos\\HyGalapagos\\HyGalapagos.gdb\\subest_reclass"
    Raster_Calculator_5_ = subest_reclass
    subest_reclass = Con(dist_acc_sub <= 3000, 5,    Con(dist_acc_sub <= 5000, 4,        Con(dist_acc_sub <= 10000, 3,            Con(dist_acc_sub <= 15000, 2,                1))))
    subest_reclass.save(Raster_Calculator_5_)


    # Process: Weighted Sum (Weighted Sum) (sa)
    Weighted_Sum = cost_raster
    cost_raster = arcpy.sa.WeightedSum(WSTable([[pv_reclass, 'VALUE', 0.5], [roads_reclass, 'VALUE', 0.15], [subest_reclass, 'VALUE', 0.15], [Aptitud_con_pediente_y_orientación_preprocesada_, 'Value', 0.2]]))
    cost_raster.save(Weighted_Sum)


    # Process: Con (Con) (sa)
    Con = pos_sites
    pos_sites = arcpy.sa.Con(cost_raster.__str__().format(**locals(),**globals())if isinstance(cost_raster, str) else cost_raster, cost_raster.__str__().format(**locals(),**globals())if isinstance(cost_raster, str) else cost_raster, "", f"VALUE >= {Valor_umbral}")
    pos_sites.save(Con)


    # Process: Int (Int) (sa)
    Output_raster = "C:\\Solar\\SolarSuitability\\SolarSA\\SolarSA.gdb\\Int_pos_site1"
    Int = Output_raster
    Output_raster = arcpy.sa.Int(pos_sites.__str__().format(**locals(),**globals())if isinstance(pos_sites, str) else pos_sites)
    Output_raster.save(Int)


    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    sites_poly = "memory\\sites_poly"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=Output_raster, out_polygon_features=sites_poly, simplify="NO_SIMPLIFY", raster_field="VALUE", create_multipart_features="SINGLE_OUTER_PART")

    # Process: Add Field (Add Field) (management)
    sites_poly_shp_2_ = arcpy.management.AddField(in_table=sites_poly, field_name="Area", field_type="LONG")[0]

    # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) (management)
    sites_poly_shp_3_ = arcpy.management.CalculateGeometryAttributes(in_features=sites_poly_shp_2_, geometry_property=[["Area", "AREA"]], area_unit="SQUARE_METERS", coordinate_system="PROJCS[\"WGS_1984_UTM_Zone_15S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",-93.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")[0]

    # Process: Reclassify (Reclassify) (sa)
    Output_raster_2_ = ""
    Reclassify = Output_raster_2_
    Output_raster_2_ = arcpy.sa.Reclassify("", "", "", "DATA")
    Output_raster_2_.save(Reclassify)


    # Process: Reclass by Table (Reclass by Table) (sa)
    Output_raster_3_ = ""
    Reclass_by_Table = Output_raster_3_
    Output_raster_3_ = arcpy.sa.ReclassByTable("", "", "", "", "", "DATA")
    Output_raster_3_.save(Reclass_by_Table)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(cellSize="Parameters\\PVOUT.tif", extent="-732167.8241 9842145.2439 -420151.902100001 10189374.8278 PROJCS[\"WGS_1984_UTM_Zone_17S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",-81.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", scratchWorkspace="C:\\Solar\\SolarSuitability\\SolarSA\\SolarSA.gdb", 
                          workspace="C:\\Solar\\SolarSuitability\\SolarSA\\SolarSA.gdb"):
        SolarSuitability(*argv[1:])
